# Form implementation generated from reading ui file 'ui/ProgressDialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProgressDialog(object):
    def setupUi(self, ProgressDialog):
        ProgressDialog.setObjectName("ProgressDialog")
        ProgressDialog.resize(394, 166)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProgressDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressLabel = QtWidgets.QLabel(parent=ProgressDialog)
        self.progressLabel.setObjectName("progressLabel")
        self.verticalLayout.addWidget(self.progressLabel)
        self.progressBar = QtWidgets.QProgressBar(parent=ProgressDialog)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.timeElapsed = QtWidgets.QLabel(parent=ProgressDialog)
        self.timeElapsed.setObjectName("timeElapsed")
        self.verticalLayout.addWidget(self.timeElapsed)
        self.estimatedTimeLabel = QtWidgets.QLabel(parent=ProgressDialog)
        self.estimatedTimeLabel.setObjectName("estimatedTimeLabel")
        self.verticalLayout.addWidget(self.estimatedTimeLabel)

        self.retranslateUi(ProgressDialog)
        QtCore.QMetaObject.connectSlotsByName(ProgressDialog)

    def retranslateUi(self, ProgressDialog):
        _translate = QtCore.QCoreApplication.translate
        ProgressDialog.setWindowTitle(_translate("ProgressDialog", "Dialog"))
        self.progressLabel.setText(_translate("ProgressDialog", "TextLabel"))
        self.timeElapsed.setText(_translate("ProgressDialog", "TextLabel"))
        self.estimatedTimeLabel.setText(_translate("ProgressDialog", "TextLabel"))
