# Form implementation generated from reading ui file 'ui/InfoDisplay.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InfoDisplay(object):
    def setupUi(self, InfoDisplay):
        InfoDisplay.setObjectName("InfoDisplay")
        InfoDisplay.resize(353, 640)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(InfoDisplay)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon = QtWidgets.QLabel(parent=InfoDisplay)
        self.icon.setObjectName("icon")
        self.horizontalLayout_2.addWidget(self.icon)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=InfoDisplay)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.sizeLabel = QtWidgets.QLabel(parent=InfoDisplay)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.sizeLabel.setFont(font)
        self.sizeLabel.setObjectName("sizeLabel")
        self.horizontalLayout.addWidget(self.sizeLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.subtitleLabel = QtWidgets.QLabel(parent=InfoDisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.subtitleLabel.setFont(font)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.verticalLayout.addWidget(self.subtitleLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=InfoDisplay)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.descriptionTextBrowser = QtWidgets.QTextBrowser(parent=InfoDisplay)
        self.descriptionTextBrowser.setObjectName("descriptionTextBrowser")
        self.verticalLayout_2.addWidget(self.descriptionTextBrowser)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(parent=InfoDisplay)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=InfoDisplay)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)

        self.retranslateUi(InfoDisplay)
        QtCore.QMetaObject.connectSlotsByName(InfoDisplay)

    def retranslateUi(self, InfoDisplay):
        _translate = QtCore.QCoreApplication.translate
        InfoDisplay.setWindowTitle(_translate("InfoDisplay", "Form"))
        self.icon.setText(_translate("InfoDisplay", "Icon"))
        self.titleLabel.setText(_translate("InfoDisplay", "Title"))
        self.sizeLabel.setText(_translate("InfoDisplay", "Size"))
        self.subtitleLabel.setText(_translate("InfoDisplay", "Subtitle"))
        self.label_4.setText(_translate("InfoDisplay", "Description"))
        self.groupBox.setTitle(_translate("InfoDisplay", "GroupBox"))
        self.groupBox_2.setTitle(_translate("InfoDisplay", "GroupBox"))
