# Form implementation generated from reading ui file 'ui/VisualizerWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VisualizerWindow(object):
    def setupUi(self, VisualizerWindow):
        VisualizerWindow.setObjectName("VisualizerWindow")
        VisualizerWindow.resize(521, 413)
        self.verticalLayout = QtWidgets.QVBoxLayout(VisualizerWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(parent=VisualizerWindow)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.webEngineWidget = QtWidgets.QWidget(parent=self.splitter)
        self.webEngineWidget.setObjectName("webEngineWidget")
        self.settingsWidget = QtWidgets.QWidget(parent=self.splitter)
        self.settingsWidget.setObjectName("settingsWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settingsWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.settingsWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.htmlButton = QtWidgets.QPushButton(parent=VisualizerWindow)
        self.htmlButton.setAutoDefault(False)
        self.htmlButton.setObjectName("htmlButton")
        self.horizontalLayout.addWidget(self.htmlButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(VisualizerWindow)
        QtCore.QMetaObject.connectSlotsByName(VisualizerWindow)

    def retranslateUi(self, VisualizerWindow):
        _translate = QtCore.QCoreApplication.translate
        VisualizerWindow.setWindowTitle(_translate("VisualizerWindow", "Dialog"))
        self.groupBox.setTitle(_translate("VisualizerWindow", "Settings"))
        self.htmlButton.setText(_translate("VisualizerWindow", "Export HTML"))
