# Form implementation generated from reading ui file 'ui/GroupSelector.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GroupSelectorDialog(object):
    def setupUi(self, GroupSelectorDialog):
        GroupSelectorDialog.setObjectName("GroupSelectorDialog")
        GroupSelectorDialog.resize(329, 532)
        self.verticalLayout = QtWidgets.QVBoxLayout(GroupSelectorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=GroupSelectorDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.group1box = QtWidgets.QGroupBox(parent=GroupSelectorDialog)
        self.group1box.setMinimumSize(QtCore.QSize(0, 175))
        self.group1box.setObjectName("group1box")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.group1box)
        self.verticalLayout_8.setContentsMargins(0, 8, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.group1ListWidget = QtWidgets.QListWidget(parent=self.group1box)
        self.group1ListWidget.setObjectName("group1ListWidget")
        self.verticalLayout_8.addWidget(self.group1ListWidget)
        self.addGroup1Button = QtWidgets.QPushButton(parent=self.group1box)
        self.addGroup1Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../icons/plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addGroup1Button.setIcon(icon)
        self.addGroup1Button.setAutoDefault(False)
        self.addGroup1Button.setFlat(True)
        self.addGroup1Button.setObjectName("addGroup1Button")
        self.verticalLayout_8.addWidget(self.addGroup1Button)
        self.verticalLayout.addWidget(self.group1box)
        self.group2box = QtWidgets.QGroupBox(parent=GroupSelectorDialog)
        self.group2box.setMinimumSize(QtCore.QSize(0, 175))
        self.group2box.setObjectName("group2box")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.group2box)
        self.verticalLayout_11.setContentsMargins(0, 8, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.group2ListWidget = QtWidgets.QListWidget(parent=self.group2box)
        self.group2ListWidget.setObjectName("group2ListWidget")
        self.verticalLayout_11.addWidget(self.group2ListWidget)
        self.addGroup2Button = QtWidgets.QPushButton(parent=self.group2box)
        self.addGroup2Button.setText("")
        self.addGroup2Button.setIcon(icon)
        self.addGroup2Button.setAutoDefault(False)
        self.addGroup2Button.setFlat(True)
        self.addGroup2Button.setObjectName("addGroup2Button")
        self.verticalLayout_11.addWidget(self.addGroup2Button)
        self.verticalLayout.addWidget(self.group2box)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.assignButton = QtWidgets.QPushButton(parent=GroupSelectorDialog)
        self.assignButton.setMinimumSize(QtCore.QSize(100, 0))
        self.assignButton.setObjectName("assignButton")
        self.horizontalLayout.addWidget(self.assignButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(GroupSelectorDialog)
        QtCore.QMetaObject.connectSlotsByName(GroupSelectorDialog)

    def retranslateUi(self, GroupSelectorDialog):
        _translate = QtCore.QCoreApplication.translate
        GroupSelectorDialog.setWindowTitle(_translate("GroupSelectorDialog", "Dialog"))
        self.label.setText(_translate("GroupSelectorDialog", "Select Groups"))
        self.group1box.setTitle(_translate("GroupSelectorDialog", "Group 1"))
        self.group2box.setTitle(_translate("GroupSelectorDialog", "Group 2"))
        self.assignButton.setText(_translate("GroupSelectorDialog", "Assign"))
